<a href="https://colab.research.google.com/github/IBM-EPBL/IBM-Project-27292-1660053205/blob/Assignments/SivaMohanReddy_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Basic Python

### 1 . Split the string

In [1]:
s = "Hi there Sam!"
print(s.split(' '))

['Hi', 'there', 'Sam!']


### 2. Use .format() to print the following string.

Output should be: The diameter of Earth is 12742 kilometers.

In [2]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


### 3. In this nest dictionary grab the word "hello"

In [3]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [4]:
import numpy as np

### 4.1 Create an array of 10 zeros?

In [5]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4.2 Create an array of 10 fives?

In [6]:
a=np.ones(10)*5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### 5. Create an array of all the even integers from 20 to 35

In [7]:
a=np.arange(20,35,2)
print(a)

[20 22 24 26 28 30 32 34]


### 6. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 7. Concatenate a and b

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a,b),axis=0))

[1 2 3 4 5 6]


# Pandas

In [10]:
import pandas as pd

### 8. Create a dataframe with 3 rows and 2 columns

In [11]:
Name = ['Siva', 'Mohan', 'Reddy']
Age = [25, 30, 26]
list_of_tuples = list(zip(Name, Age))
df = pd.DataFrame(list_of_tuples,columns=['Name', 'Age'])
print(df)

    Name  Age
0   Siva   25
1  Mohan   30
2  Reddy   26


### 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [12]:
a=pd.date_range(start ='1-1-2023',end ='10-2-2023')   
print(a)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')


### 10. Create 2D list to DataFrame

In [13]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns =['Index','Name', 'number'])
print(df)

   Index Name  number
0      1  aaa      22
1      2  bbb      25
2      3  ccc      24
